### ISSUE TITLE
Missing `n` in  `backgroudColor`

### ISSUE THREAD

**Issue by gjwgit** [yassinedevop/neon_circular_timer#3]
Line 20-21 of lib/neon_circular_timer.dart

```
  /// Filling Color for Countdown circle.
  final Color? backgroudColor;
```

That should be `backgroundColor` (with an `n`)?

**Comment by yassinedevop** [comment]
Thank you for the remark, I fixed it.

**Comment by gjwgit** [comment]
Thanks. And thanks for sharing a really useful and good looking timer.
